### ISSUE TITLE
Intermittent failures downloading Neurovault decoding API

### ISSUE THREAD

**Issue by bcipolli** [neurosynth/neurosynth-web#99] opened 2015-11-16 22:57 UTC
I am reimplementing the neurovault ICA analysis that @gaelvaroquax and @chrisfilo implemented for their fronteirs paper:
https://github.com/NeuroVault/neurovault_analysis

I have 1470 neurovault images that I'm downloading neurosynth decoding terms for (one image at a time). Every so often, I get an invalid JSON back from neurosynth. The error isn't exactly the same every time, but is always around line 8900.

An example:
```
  {
      "analysis": "representation",
      "r": 0.018
    },
    {
      "analysis": "representations",
  : "requires",
      "r": -0.004
    },
```
![image](https://cloud.githubusercontent.com/assets/4072455/11197357/c286c598-8c71-11e5-8740-3138fd78d0fe.png)

Always the JSON error is some weird insertion / folding like this, but never exactly the same. And if I re-run the download for the same image, it usually gives a valid JSON blob.

**Comment by vsoch** [comment] 2015-11-16 23:01
Are you running plot_ica.py?

**Comment by bcipolli** [comment] 2015-11-16 23:04
Nope, I'm running my ported version:
https://github.com/bcipolli/nilearn/blob/neurovault-downloader/examples/connectivity/plot_ica_neurovault.py

**Comment by vsoch** [comment] 2015-11-16 23:07
cool, I'll take a look and see if I can help.

**Comment by vsoch** [comment] 2015-11-16 23:08
are the maps you are using somewhere?

**Comment by vsoch** [comment] 2015-11-16 23:16
Hmm, it seems like there have been problems with the file fetcher from nilearn. Did you try just retrieving the json without using the fetcher?

**Comment by vsoch** [comment] 2015-11-16 23:22
Try like:

      from urllib2 import Request, urlopen
      import json

      def get_url(url):
          request = Request(url)
          response = urlopen(request)
          content = response.read()
          return json.loads(content.decode("utf-8"))

      url = "http://neurosynth.org/decode/data/?neurovault=444"
      mrjson = get_url(url)

**Comment by bcipolli** [comment] 2015-11-17 00:09
>Hmm, it seems like there have been problems with the file fetcher from nilearn. Did you try just retrieving the json without using the fetcher?

Not sure what this means; I'm not having any fetcher problems... So no, I didn't use anything but the fetcher code! That's the PR I'm working on, so ... if it's broken I shoulda fixed it :)

**Comment by bcipolli** [comment] 2015-11-17 00:12
>are the maps you are using somewhere?

If you add my `nilearn` and checkout the branch, it should run... but it'll download all the neurovault images first, which sucks. 

If you want a minimum steps to reproduce, I can try to come up with it, but might have to wait until tomorrow.

**Comment by vsoch** [comment] 2015-11-17 00:12
Unless you can reproduce the errored json in a browser, my gut is saying that the issue has to do with reading the url, and not the content of the url itself.

**Comment by vsoch** [comment] 2015-11-17 00:13
A good start would be to add a print line to see the specific image triggering the error, and then inspect the json in the browser. If there is no error, it's not a fault of the neurosynth API, it's whatever method is retrieving it.

**Comment by bcipolli** [comment] 2015-11-17 00:18
>Unless you can reproduce the errored json in a browser, my gut is saying that the issue has to do with reading the url, and not the content of the url itself.

Hmm, OK... the `nilearn` fetching API has been very well tested, so I can't imagine why it'd suddenly be failing on 1/100 JSON responses randomly. Anyway, it's not a very important issue--easy enough to work around.

>A good start would be to add a print line to see the specific image triggering the error, and then inspect the json in the browser.

That won't work, as the error isn't reproducible. If I run the same download command twice and the first one fails, the second one likely succeeds--even on the same image.

**Comment by vsoch** [comment] 2015-11-17 00:26
There are two possibilities here - either there is a bug in the page itself, or retrieving the page. It would be fairly simple to test the second by replacing the fetcher code with a simplified version to see if you get the same error. If not, it's the retrieval.  I would try it many times for the same query, and see if you get a consistent result (even plain text). If you consistently get different raw text with the same call with the most simplified retrieval method (not the fetcher) then it is something about the page itself. I don't know else to help other than those suggestions...

**Comment by tyarkoni** [comment] 2015-11-17 00:26
Haven't run into this issue before on the Neurosynth side, but stranger
things have happened... if you can reproduce it using just the urlib or
requests libraries, leery me know and I'll look into it.

**Comment by vsoch** [comment] 2015-11-17 00:31
My instinct is that you are trying to read the file before it's done writing. Instead of reading from the page directly, the fetcher is saving it first, and then loading the saved file. If you load the json by reading from the page, you will likely not have this error.

The simple function I gave you above - I just ran it 100 times, and I did not get any error with my json loading.

**Comment by vsoch** [comment] 2015-11-17 00:35
You could also try putting a second pause after the command to get the "elevations," before trying to read, and see if that works. If so, it is more evidence of an issue with the timing of reading/writing the files.

**Comment by bcipolli** [comment] 2015-11-17 00:36
k, will let you know, thanks!

**Comment by vsoch** [comment] 2015-11-17 00:38
cool! sounds good :)

**Comment by tyarkoni** [comment] 2015-11-17 00:44
Yeah, this sounds right. The nilearn lib is probably not waiting for the
file handle to close on write before reading from it again. Sleeping for a
bit will usually not fix this if the code is single threaded; I suggest
using the requests lib like Vanessa said.

**Comment by tyarkoni** [comment] 2015-11-17 01:10
Closing the issue, but please re-open if it turns out to be a Neurosynth issue.

**Closed by tyarkoni** 2015-11-17 01:10 UTC

**Comment by tyarkoni** [comment] 2015-11-17 01:13
By the way, the old API you're calling is deprecated. You can now use the better-documented swaggerified API:

http://neurosynth.org/api/v2/

E.g.,

http://neurosynth.org/api/v2/decode/?neurovault=309

**Comment by tyarkoni** [comment] 2015-11-17 01:15
It returns a different, more compact JSON representation, so while you'll need to rewrite your code to handle the new results, it's conceivable you won't run into the same issue any more.
